name: Build MasterTuning Remote

on:
  push:
    branches: [master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
